/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as FunnelRouteImport } from './routes/funnel'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSpeechRouteImport } from './routes/api/speech'
import { Route as ApiExecutiveChatRouteImport } from './routes/api/executive-chat'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AppStudentsRouteImport } from './routes/_app/students'
import { Route as AppLeadsRouteImport } from './routes/_app/leads'
import { Route as AppFleetRouteImport } from './routes/_app/fleet'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCarriersRouteImport } from './routes/_app/carriers'
import { Route as AppAgentsFundingRouteImport } from './routes/_app/agents.funding'
import { Route as AppAgentsAdmissionsRouteImport } from './routes/_app/agents.admissions'

const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const FunnelRoute = FunnelRouteImport.update({
  id: '/funnel',
  path: '/funnel',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpeechRoute = ApiSpeechRouteImport.update({
  id: '/api/speech',
  path: '/api/speech',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExecutiveChatRoute = ApiExecutiveChatRouteImport.update({
  id: '/api/executive-chat',
  path: '/api/executive-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppFleetRoute = AppFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCarriersRoute = AppCarriersRouteImport.update({
  id: '/carriers',
  path: '/carriers',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsFundingRoute = AppAgentsFundingRouteImport.update({
  id: '/agents/funding',
  path: '/agents/funding',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsAdmissionsRoute = AppAgentsAdmissionsRouteImport.update({
  id: '/agents/admissions',
  path: '/agents/admissions',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/funnel': typeof FunnelRoute
  '/programs': typeof ProgramsRoute
  '/carriers': typeof AppCarriersRoute
  '/dashboard': typeof AppDashboardRoute
  '/fleet': typeof AppFleetRoute
  '/leads': typeof AppLeadsRoute
  '/students': typeof AppStudentsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/executive-chat': typeof ApiExecutiveChatRoute
  '/api/speech': typeof ApiSpeechRoute
  '/agents/admissions': typeof AppAgentsAdmissionsRoute
  '/agents/funding': typeof AppAgentsFundingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/funnel': typeof FunnelRoute
  '/programs': typeof ProgramsRoute
  '/carriers': typeof AppCarriersRoute
  '/dashboard': typeof AppDashboardRoute
  '/fleet': typeof AppFleetRoute
  '/leads': typeof AppLeadsRoute
  '/students': typeof AppStudentsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/executive-chat': typeof ApiExecutiveChatRoute
  '/api/speech': typeof ApiSpeechRoute
  '/agents/admissions': typeof AppAgentsAdmissionsRoute
  '/agents/funding': typeof AppAgentsFundingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/funnel': typeof FunnelRoute
  '/programs': typeof ProgramsRoute
  '/_app/carriers': typeof AppCarriersRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/fleet': typeof AppFleetRoute
  '/_app/leads': typeof AppLeadsRoute
  '/_app/students': typeof AppStudentsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/executive-chat': typeof ApiExecutiveChatRoute
  '/api/speech': typeof ApiSpeechRoute
  '/_app/agents/admissions': typeof AppAgentsAdmissionsRoute
  '/_app/agents/funding': typeof AppAgentsFundingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/careers'
    | '/contact'
    | '/funnel'
    | '/programs'
    | '/carriers'
    | '/dashboard'
    | '/fleet'
    | '/leads'
    | '/students'
    | '/api/chat'
    | '/api/executive-chat'
    | '/api/speech'
    | '/agents/admissions'
    | '/agents/funding'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/careers'
    | '/contact'
    | '/funnel'
    | '/programs'
    | '/carriers'
    | '/dashboard'
    | '/fleet'
    | '/leads'
    | '/students'
    | '/api/chat'
    | '/api/executive-chat'
    | '/api/speech'
    | '/agents/admissions'
    | '/agents/funding'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/about'
    | '/auth'
    | '/careers'
    | '/contact'
    | '/funnel'
    | '/programs'
    | '/_app/carriers'
    | '/_app/dashboard'
    | '/_app/fleet'
    | '/_app/leads'
    | '/_app/students'
    | '/api/chat'
    | '/api/executive-chat'
    | '/api/speech'
    | '/_app/agents/admissions'
    | '/_app/agents/funding'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  FunnelRoute: typeof FunnelRoute
  ProgramsRoute: typeof ProgramsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiExecutiveChatRoute: typeof ApiExecutiveChatRoute
  ApiSpeechRoute: typeof ApiSpeechRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funnel': {
      id: '/funnel'
      path: '/funnel'
      fullPath: '/funnel'
      preLoaderRoute: typeof FunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/speech': {
      id: '/api/speech'
      path: '/api/speech'
      fullPath: '/api/speech'
      preLoaderRoute: typeof ApiSpeechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/executive-chat': {
      id: '/api/executive-chat'
      path: '/api/executive-chat'
      fullPath: '/api/executive-chat'
      preLoaderRoute: typeof ApiExecutiveChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/students': {
      id: '/_app/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fleet': {
      id: '/_app/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof AppFleetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/carriers': {
      id: '/_app/carriers'
      path: '/carriers'
      fullPath: '/carriers'
      preLoaderRoute: typeof AppCarriersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/funding': {
      id: '/_app/agents/funding'
      path: '/agents/funding'
      fullPath: '/agents/funding'
      preLoaderRoute: typeof AppAgentsFundingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/admissions': {
      id: '/_app/agents/admissions'
      path: '/agents/admissions'
      fullPath: '/agents/admissions'
      preLoaderRoute: typeof AppAgentsAdmissionsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCarriersRoute: typeof AppCarriersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFleetRoute: typeof AppFleetRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppStudentsRoute: typeof AppStudentsRoute
  AppAgentsAdmissionsRoute: typeof AppAgentsAdmissionsRoute
  AppAgentsFundingRoute: typeof AppAgentsFundingRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCarriersRoute: AppCarriersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFleetRoute: AppFleetRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppStudentsRoute: AppStudentsRoute,
  AppAgentsAdmissionsRoute: AppAgentsAdmissionsRoute,
  AppAgentsFundingRoute: AppAgentsFundingRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  FunnelRoute: FunnelRoute,
  ProgramsRoute: ProgramsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiExecutiveChatRoute: ApiExecutiveChatRoute,
  ApiSpeechRoute: ApiSpeechRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
